# Modelos de Regressão

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor

In [2]:
df = pd.read_csv('kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
df.shape

(21613, 21)

In [4]:
df = df[['id','date','price','bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront']]
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0

In [5]:
columns_to_drop = ['id','date']
df = df.drop(columns=columns_to_drop)
df.head()

      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront
0  221900.0         3       1.00         1180      5650     1.0           0
1  538000.0         3       2.25         2570      7242     2.0           0
2  180000.0         2       1.00          770     10000     1.0           0
3  604000.0         4       3.00         1960      5000     1.0           0
4  510000.0         3       2.00         1680      8080     1.0           0

In [6]:
rows,cols = df.shape
print(f"O dataset possui {rows} linhas e {cols} colunas.")

O dataset possui 21613 linhas e 7 colunas.

In [7]:
x = df.drop(columns='price')
y = df['price']

In [8]:
x.head(),y.head()

(   bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront
 0         3       1.00         1180      5650     1.0           0
 1         3       2.25         2570      7242     2.0           0
 2         2       1.00          770     10000     1.0           0
 3         4       3.00         1960      5000     1.0           0
 4         3       2.00         1680      8080     1.0           0,
 0    221900.0
 1    538000.0
 2    180000.0
 3    604000.0
 4    510000.0
 Name: price, dtype: float64)

In [9]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [11]:
len(y_train),len(y_test)

(15129, 6484)

## Regressão Linear

In [12]:
lr_model = LinearRegression()
lr_model.fit(x_train,y_train)

y_pred = lr_model.predict(x_test)

In [14]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) 
mape = mean_absolute_percentage_error(y_test, y_pred)

print(f"MSE : {mse} \nRMSE: {rmse} \nMAPE: {mape}")

MSE : 65997533248.17038
RMSE: 256899.85061920603
MAPE: 0.3479945245207993

## K-NN Regressor

**K=7**

In [16]:
knr_model = KNeighborsRegressor(n_neighbors=7, metric='euclidean')
knr_model.fit(x_train,y_train)

y_pred_knr = knr_model.predict(x_test)

In [17]:
mape = mean_absolute_percentage_error(y_test, y_pred_knr)
print(f"MAPE: {mape}")

MAPE: 0.3265608703439842

**K=11**

In [18]:
knr_model = KNeighborsRegressor(n_neighbors=11, metric='euclidean')
knr_model.fit(x_train,y_train)

y_pred_knr = knr_model.predict(x_test)

In [19]:
mape = mean_absolute_percentage_error(y_test, y_pred_knr)
print(f"MAPE: {mape}")

MAPE: 0.3227526719852916

## SVM Support Vector Machines for Regression

In [22]:
svr_model = SVR()
svr_model.fit(x_train,y_train)
y_pred_svr = svr_model.predict(x_test)

In [23]:
mape = mean_absolute_percentage_error(y_test, y_pred_svr)
print(f"MAPE: {mape}")

MAPE: 0.4249428261761056

**Testing other kernel**

In [24]:
svr_model = SVR(kernel='linear', C=100)
svr_model.fit(x_train,y_train)
y_pred_svr = svr_model.predict(x_test)

In [25]:
mape = mean_absolute_percentage_error(y_test, y_pred_svr)
print(f"MAPE: {mape}")

MAPE: 0.3253353439804244

## Árvore de Regressão

In [27]:
dcr_model = DecisionTreeRegressor()
dcr_model.fit(x_train,y_train)
y_pred_dcr = dcr_model.predict(x_test)

In [29]:
mape = mean_absolute_percentage_error(y_test, y_pred_dcr)
print(f"MAPE: {mape}")

MAPE: 0.41647449843470363

## XGBoost

In [31]:
xgb_model = XGBRegressor()
xgb_model.fit(x_train,y_train)
y_pred_xgb = xgb_model.predict(x_test)

In [32]:
mape = mean_absolute_percentage_error(y_test, y_pred_xgb)
print(f"MAPE: {mape}")

MAPE: 0.3157134847759837

In [34]:
params = {
    'n_estimators': 100,
    'max_depth': 6,
    'learning_rate': 0.01
}

In [35]:
xgb_model = XGBRegressor(**params)
xgb_model.fit(x_train,y_train)
y_pred_xgb = xgb_model.predict(x_test)

In [36]:
mape = mean_absolute_percentage_error(y_test, y_pred_svr)
print(f"MAPE: {mape}")

MAPE: 0.3253353439804244